# model settings
norm_cfg = dict(type="SyncBN", requires_grad=True)
model = dict(
    type="CustomEncoderDecoder",
    data_preprocessor=None,
    pretrained=None,
    backbone=dict(
        type="MixVisionTransformer",
        in_channels=12,
        embed_dims=32,
        num_stages=4,
        num_layers=[2, 2, 2, 2],
        num_heads=[1, 2, 5, 8],
        patch_sizes=[7, 3, 3, 3],
        sr_ratios=[8, 4, 2, 1],
        out_indices=(0, 1, 2, 3),
        mlp_ratio=4,
        qkv_bias=True,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.1,
    ),
    decode_head=dict(
        type="CustomSegformerHead",
        in_channels=[32, 64, 160, 256],
        in_index=[0, 1, 2, 3],
        channels=256,
        dropout_ratio=0.1,
        num_classes=1,
        aux_classes=11,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=None,
    ),
    train_cfg=dict(),
    test_cfg=dict(),
)
